services:
  nginx-proxy:
    image: docker.io/nginxproxy/nginx-proxy
    ports:
      - "8080:80/tcp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - shop-it

  client:
    image: localhost/shop-it_client:prod
    expose:
      - "8080"
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - shop-it
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/
      - VIRTUAL_PORT=8080

  api:
    image: localhost/shop-it_api:prod
    expose:
      - "80"
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/html:rw
    networks:
      - shop-it
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/api/
      - VIRTUAL_DEST=/
      - VIRTUAL_PORT=80

  db:
    image: docker.io/mariadb:10.7.8
    restart: unless-stopped
    expose:
      - "3306"
    environment:
      - MARIADB_DATABASE=shopit
      - MARIADB_ROOT_PASSWORD=12345
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      shop-it:
        aliases:
          - shopitdb

volumes:
  mariadb:

networks:
  shop-it:
    driver: bridge
