START TRANSACTION;
INSERT INTO departments(department_id, name) VALUES (1, "Alta Verapaz");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (1, "Cobán", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (2, "San Pedro Carchá", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (3, "San Juan Chamelco", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (4, "San Cristóbal Verapaz", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (5, "Tactic", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (6, "Tucuru", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (7, "Tamahú", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (8, "Panzós", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (9, "Senahú", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (10, "Cahabón", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (11, "Lanquín", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (12, "Chahal", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (13, "Fray Bartolomé de las Casas", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (14, "Chisec", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (15, "Santa Cruz Verapaz", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (16, "Santa Catalina La Tinta", 1);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (17, "Raxruhá", 1);
INSERT INTO departments(department_id, name) VALUES (2, "Baja Verapaz");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (18, "Cubulco", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (19, "Santa Cruz el Chol", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (20, "Granados", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (21, "Purulhá", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (22, "Rabinal", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (23, "Salamá", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (24, "San Miguel Chicaj", 2);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (25, "San Jerónimo", 2);
INSERT INTO departments(department_id, name) VALUES (3, "Chimaltenango");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (26, "Chimaltenango", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (27, "San José Poaquíl", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (28, "San Martín Jilotepeque", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (29, "San Juan Comalapa", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (30, "Santa Apolonia", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (31, "Tecpán Guatemala", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (32, "Patzún", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (33, "Pochuta", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (34, "Patzicía", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (35, "Santa Cruz Balanyá", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (36, "Acatenango", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (37, "San Pedro Yepocapa", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (38, "San Andrés Itzapa", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (39, "Parramos", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (40, "Zaragoza", 3);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (41, "El Tejar", 3);
INSERT INTO departments(department_id, name) VALUES (4, "Chiquimula");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (42, "Chiquimula", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (43, "Jocotán", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (44, "Esquipulas", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (45, "Camotán", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (46, "Quezaltepeque", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (47, "Olopa", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (48, "Ipala", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (49, "San Juan Ermita", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (50, "Concepción Las Minas", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (51, "San Jacinto", 4);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (52, "San José la Arada", 4);
INSERT INTO departments(department_id, name) VALUES (5, "El Progreso");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (53, "El Jícaro", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (54, "Guastatoya", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (55, "Morazán", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (56, "Sanarate", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (57, "Sansare", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (58, "San Agustín Acasaguastlán", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (59, "San Antonio La Paz", 5);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (60, "San Cristóbal Acasaguastlán", 5);
INSERT INTO departments(department_id, name) VALUES (6, "Escuintla");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (61, "Escuintla", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (62, "Guanagazapa", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (63, "Iztapa", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (64, "La Democracia", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (65, "La Gomera", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (66, "Masagua", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (67, "Nueva Concepción", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (68, "Palín", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (69, "San José", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (70, "San Vicente Pacaya", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (71, "Santa Lucía Cotzumalguapa", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (72, "Sipacate", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (73, "Siquinalá", 6);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (74, "Tiquisate", 6);
INSERT INTO departments(department_id, name) VALUES (7, "Guatemala");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (75, "Guatemala", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (76, "Villa Nueva", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (77, "Mixco", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (78, "Santa Catarina Pinula", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (79, "San José Pinula", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (80, "San José del Golfo", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (81, "Palencia", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (82, "Chinautla", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (83, "San Pedro Ayampuc", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (84, "San Pedro Sacatepéquez", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (85, "San Juan Sacatepéquez", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (86, "San Raymundo", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (87, "Chuarrancho", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (88, "Fraijanes", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (89, "Amatitlán", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (90, "Villa Canales", 7);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (91, "San Miguel Petapa", 7);
INSERT INTO departments(department_id, name) VALUES (8, "Huehuetenango");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (92, "Aguacatán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (93, "Chiantla", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (94, "Colotenango", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (95, "Concepción Huista", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (96, "Cuilco", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (97, "Huehuetenango", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (98, "Jacaltenango", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (99, "La Democracia", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (100, "La Libertad", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (101, "Malacatancito", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (102, "Nentón", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (103, "Petatán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (104, "San Antonio Huista", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (105, "San Gaspar Ixchil", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (106, "Ixtahuacán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (107, "San Juan Atitán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (108, "San Juan Ixcoy", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (109, "San Mateo Ixtatán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (110, "San Miguel Acatán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (111, "San Pedro Necta", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (112, "San Pedro Soloma", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (113, "San Rafael La Independencia", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (114, "San Rafael Petzal", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (115, "San Sebastián Coatán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (116, "San Sebastián Huehuetenango", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (117, "Santa Ana Huista.", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (118, "Santa Bárbara", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (119, "Barillas", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (120, "Santa Eulalia", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (121, "Santiago Chimaltenango", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (122, "Tectitán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (123, "Todos Santos Cuchumatán", 8);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (124, "Unión Cantinil", 8);
INSERT INTO departments(department_id, name) VALUES (9, "Izabal");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (125, "Puerto Barrios", 9);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (126, "Livingston", 9);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (127, "El Estor", 9);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (128, "Morales", 9);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (129, "Los Amates", 9);
INSERT INTO departments(department_id, name) VALUES (10, "Jalapa");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (130, "Jalapa", 10);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (131, "Mataquescuintla", 10);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (132, "Monjas", 10);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (133, "San Carlos Alzatate", 10);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (134, "San Luis Jilotepeque", 10);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (135, "San Pedro Pinula", 10);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (136, "San Manuel Chaparrón", 10);
INSERT INTO departments(department_id, name) VALUES (11, "Jutiapa");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (137, "Agua Blanca", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (138, "Asunción Mita", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (139, "Atescatempa", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (140, "Comapa", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (141, "Conguaco", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (142, "El Adelanto", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (143, "El Progreso", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (144, "Jalpatagua", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (145, "Jerez", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (146, "Jutiapa", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (147, "Moyuta", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (148, "Pasaco", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (149, "Quesada", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (150, "San José Acatempa", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (151, "Santa Catarina Mita", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (152, "Yupiltepeque", 11);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (153, "Zapotitlán", 11);
INSERT INTO departments(department_id, name) VALUES (12, "Petén");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (154, "Dolores", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (155, "Flores", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (156, "La Libertad", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (157, "Melchor de Mencos", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (158, "Poptún", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (159, "San Andrés", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (160, "San Benito", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (161, "San Francisco", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (162, "San José", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (163, "San Luis", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (164, "Santa Ana", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (165, "Sayaxché", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (166, "Las Cruces", 12);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (167, "El Chal", 12);
INSERT INTO departments(department_id, name) VALUES (13, "Quetzaltenango");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (168, "Almolonga", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (169, "Cabricán", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (170, "Cajolá", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (171, "Cantel", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (172, "Coatepeque", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (173, "Colomba", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (174, "Concepción Chiquirichapa", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (175, "El Palmar", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (176, "Flores Costa Cuca", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (177, "Génova", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (178, "Huitán", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (179, "La Esperanza", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (180, "Olintepeque", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (181, "Palestina de Los Altos", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (182, "Quetzaltenango", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (183, "Salcajá", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (184, "San Carlos Sija", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (185, "San Juan Ostuncalco", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (186, "San Francisco La Unión", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (187, "San Martín Sacatepéquez", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (188, "San Mateo", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (189, "San Miguel Sigüilá", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (190, "Sibilia", 13);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (191, "Zunil", 13);
INSERT INTO departments(department_id, name) VALUES (14, "Quiché");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (192, "Santa Cruz del Quiché", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (193, "Canillá", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (194, "Chajul", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (195, "Chicamán", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (196, "Chiché", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (197, "Chichicastenango", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (198, "Chinique", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (199, "Cunén", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (200, "Ixcán", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (201, "Joyabaj", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (202, "Pachalum", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (203, "Patzité", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (204, "Sacapulas", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (205, "San Andrés Sajcabajá", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (206, "San Antonio Ilotenango", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (207, "San Bartolomé Jocotenango", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (208, "San Juan Cotzal", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (209, "San Pedro Jocopilas", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (210, "Santa María Nebaj", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (211, "Uspantán", 14);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (212, "Zacualpa", 14);
INSERT INTO departments(department_id, name) VALUES (15, "Retalhuleu");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (213, "Retalhuleu", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (214, "San Sebastián", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (215, "Santa Cruz Muluá", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (216, "San Martín Zapotitlán", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (217, "San Felipe", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (218, "San Andrés Villa Seca", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (219, "Champerico", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (220, "Nuevo San Carlos", 15);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (221, "El Asintal", 15);
INSERT INTO departments(department_id, name) VALUES (16, "Sacatepéquez");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (222, "Alotenango", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (223, "Antigua Guatemala", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (224, "Ciudad Vieja", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (225, "Jocotenango", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (226, "Magdalena Milpas Altas", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (227, "Pastores", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (228, "San Antonio Aguas Calientes", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (229, "San Bartolomé Milpas Altas", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (230, "San Lucas Sacatepéquez", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (231, "San Miguel Dueñas", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (232, "Santa Catarina Barahona", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (233, "Santa Lucía Milpas Altas", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (234, "Santa María de Jesús", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (235, "Santiago Sacatepéquez", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (236, "Santo Domingo Xenacoj", 16);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (237, "Sumpango", 16);
INSERT INTO departments(department_id, name) VALUES (17, "San Marcos");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (238, "San Marcos", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (239, "Ayutla", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (240, "Catarina", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (241, "Comitancillo", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (242, "Concepción Tutuapa", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (243, "El Quetzal", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (244, "El Rodeo", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (245, "El Tumbador", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (246, "Ixchiguán", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (247, "La Reforma", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (248, "Malacatán", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (249, "Nuevo Progreso", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (250, "Ocós", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (251, "Pajapita", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (252, "Esquipulas Palo Gordo", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (253, "San Antonio Sacatepéquez", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (254, "San Cristóbal Cucho", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (255, "San José Ojetenam", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (256, "San Lorenzo", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (257, "San Miguel Ixtahuacán", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (258, "San Pablo", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (259, "San Pedro Sacatepéquez", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (260, "San Rafael Pie de la Cuesta", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (261, "Sibinal", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (262, "Sipacapa", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (263, "Tacaná", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (264, "Tajumulco", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (265, "Tejutla", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (266, "Río Blanco", 17);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (267, "La Blanca", 17);
INSERT INTO departments(department_id, name) VALUES (18, "Santa Rosa");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (268, "Barberena", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (269, "Casillas", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (270, "Chiquimulilla", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (271, "Cuilapa", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (272, "Guazacapán", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (273, "Nueva Santa Rosa", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (274, "Oratorio", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (275, "Pueblo Nuevo Viñas", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (276, "San Juan Tecuaco", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (277, "San Rafael Las Flores", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (278, "Santa Cruz Naranjo", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (279, "Santa María Ixhuatán", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (280, "Santa Rosa de Lima", 18);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (281, "Taxisco", 18);
INSERT INTO departments(department_id, name) VALUES (19, "Sololá");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (282, "Sololá", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (283, "Concepción", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (284, "Nahualá", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (285, "Panajachel", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (286, "San Andrés Semetabaj", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (287, "San Antonio Palopó", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (288, "San José Chacayá", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (289, "San Juan La Laguna", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (290, "San Lucas Tolimán", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (291, "San Marcos La Laguna", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (292, "San Pablo La Laguna", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (293, "San Pedro La Laguna", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (294, "Santa Catarina Ixtahuacán", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (295, "Santa Catarina Palopó", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (296, "Santa Clara La Laguna", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (297, "Santa Cruz La Laguna", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (298, "Santa Lucía Utatlán", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (299, "Santa María Visitación", 19);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (300, "Santiago Atitlán", 19);
INSERT INTO departments(department_id, name) VALUES (20, "Suchitepéquez");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (301, "Chicacao", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (302, "Cuyotenango", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (303, "Mazatenango", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (304, "Patulul", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (305, "Pueblo Nuevo", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (306, "Río Bravo", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (307, "Samayac", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (308, "San Antonio Suchitepéquez", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (309, "San Bernardino", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (310, "San Francisco Zapotitlán", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (311, "San Gabriel", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (312, "San José El Ídolo", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (313, "San José La Máquina", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (314, "San Juan Bautista", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (315, "San Lorenzo", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (316, "San Miguel Panán", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (317, "San Pablo Jocopilas", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (318, "Santa Bárbara", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (319, "Santo Domingo Suchitepéquez", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (320, "Santo Tomás La Unión", 20);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (321, "Zunilito", 20);
INSERT INTO departments(department_id, name) VALUES (21, "Totonicapán");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (322, "Momostenango", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (323, "San Andrés Xecul", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (324, "San Bartolo", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (325, "San Cristóbal Totonicapán", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (326, "San Francisco El Alto", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (327, "Santa Lucía La Reforma", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (328, "Santa María Chiquimula", 21);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (329, "Totonicapán", 21);
INSERT INTO departments(department_id, name) VALUES (22, "Zacapa");
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (330, "Cabañas", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (331, "Estanzuela", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (332, "Gualán", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (333, "Huité", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (334, "La Unión", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (335, "Río Hondo", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (336, "San Diego", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (337, "San Jorge", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (338, "Teculután", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (339, "Usumatlán", 22);
INSERT INTO municipalities(municipality_id, name, department_id) VALUES (340, "Zacapa", 22);
COMMIT;